//
// Jest configuration.
//
// Note: 'setupFilesAfterEnv' replaced 'setupTestFrameworkScriptFile' in jest 24.
//       This file named the old key against jest 26, so setup.js was never
//       loaded -- which is why the sessionStorage shim it installs was absent
//       and the console.error trap never armed.
//
// Note: 'testEnvironment' is named explicitly rather than relying on the
//       default. jest 26 defaulted to jsdom, but jest 27 moved the default to
//       node, so on the jest 29 used here the DOM has to be asked for or every
//       component test fails with 'document is not defined'.
//
// Note: the component tests use @testing-library/react rather than enzyme.
//       Enzyme has no React 18 adapter and has been unmaintained since 2021,
//       while this project is on React 18 -- the old suite was configured with
//       an adapter for React 17 and could not run at all.
//

//
// Pin the clock's zone for the whole run.
//
// This codebase reasons in eastern time throughout -- dst.js, the ingest schedule,
// and the chart aggregators all bucket by an eastern wall clock -- so the modules
// under test genuinely behave differently depending on where the suite runs. The
// daily aggregation in trigger/toggle_chart_scale/candlestick.js, for instance,
// splits one trading day across two buckets when the runtime zone is Asia/Tokyo.
//
// This has to be set HERE rather than in setup.js or a test file: jest gives each
// test file a COPY of 'process', so assigning process.env.TZ from inside one sets
// the copy without invalidating v8's timezone cache, and Date carries on in the
// old zone. jest.config.js is evaluated in the real process, before the workers
// are forked, so the value is inherited as a genuine environment variable.
//
process.env.TZ = 'America/New_York';

module.exports = {
    'verbose': true,
    'collectCoverage': true,
    'coverageDirectory': "<rootDir>",
    'testEnvironment': "jsdom",
    //
    // Note: 'moduleDirectories' is deliberately NOT set. It used to pin
    //       resolution to "<rootDir>/node_modules", an ABSOLUTE path, which
    //       replaces jest's default of the relative "node_modules" and so
    //       disables node's normal upward walk. Anything npm nests rather than
    //       hoists then cannot be resolved -- jest 29 fails to start at all with
    //       "Cannot find module 'expect'", because expect lands in
    //       node_modules/@jest/expect/node_modules/expect.
    //
    //
    // 'is_local.js' is GENERATED by the deploy script and gitignored, so it does
    // not exist in a clean checkout -- but four modules inside the
    // route/main-route.jsx graph import it, so any test touching the route table
    // fails to load with:
    //
    //     Cannot find module '../../../is_local.js'
    //
    // Locally the suite can pass by accident, because a previous build leaves the
    // file behind. Mapping it to a committed stub is what makes the suite
    // hermetic rather than dependent on build state.
    //
    'moduleNameMapper': {
        '^.*/is_local\\.js$': "<rootDir>/__stubs__/is_local.js",
    },
    //
    // setup.js installs the storage shims and the console trap; jest-dom adds
    // the DOM matchers (toBeInTheDocument, toHaveValue, ...). Order matters
    // only in that both must run after the environment exists.
    //
    'setupFilesAfterEnv': [
        "<rootDir>/setup.js",
        "@testing-library/jest-dom",
    ],
    //
    // Note: coverage is collected from the source tree rather than from
    //       whatever a test happened to import, so a component with no test at
    //       all is reported at 0% instead of being silently absent from the
    //       report.
    //
    // Fail the run if coverage drops, rather than only reporting it.
    //
    // A flat 86% baseline on all four metrics. Current figures are 92.76 statements /
    // 86.68 branches / 87.34 functions / 92.94 lines, so this is the mechanism that
    // actually holds coverage -- the README badge is a static number and will go stale
    // on its own.
    //
    // Note: branches and functions are again the two that bind -- 23 branches and 10
    //       functions of room at the time this was raised from 85. Statements and
    //       lines carry ~6 points of slack, so in practice a build reddens on a new
    //       untested BRANCH long before anything else. That is the point of a
    //       baseline rather than a trailing floor, but it means new work needs its
    //       tests in the same commit, not a follow-up.
    //
    // Note: the figures still drift slightly with the clock, because a few suites
    //       build their fixtures from the rolling window and so reach different
    //       schedule branches at different hours. It used to be worse: stream.jsx
    //       picks a default rate from whether the market is open, and that block was
    //       measured only in whichever state the run happened to catch. Both states
    //       are pinned now (stream.test.jsx fakes Date around the constructor), which
    //       is also what stopped that suite failing every weekday afternoon.
    //
    // Note: raising this from 85 to 86 was paid for with ~35 new branch assertions --
    //       stream.jsx's listing figures (streamCoverage had none at all), its
    //       reset_stream and control tray, and area-chart.jsx's prop syncing. Do not
    //       raise it again without measuring first.
    //
    // Raise these as coverage rises. They are a floor, not a target.
    //
    // Note: measure against the COMMITTED tree before raising these, not against a
    //       working copy. Uncommitted test files still get collected, so a local
    //       run can report a figure CI cannot reach -- while these numbers were
    //       being chosen the working copy read 68.68% and HEAD read 42.16%, an
    //       18-file gap. Setting the floor from the former would have failed the
    //       build on the first push. A throwaway worktree at HEAD is the cheap way
    //       to check:
    //
    //           git worktree add --detach /tmp/check HEAD
    //           ln -s "$PWD/node_modules" /tmp/check/jsx/node_modules
    //
    'coverageThreshold': {
        global: {
            statements: 86,
            branches: 86,
            functions: 86,
            lines: 86,
        },
    },
    //
    // jest's defaults plus 'json-summary'. The summary is what scripts/coverage_badge.py
    // reads to build the badge payload, and it is the only reporter that states the
    // overall figure as a number rather than as text to be scraped.
    //
    // Every one of these lands in <rootDir> and every one is gitignored.
    //
    'coverageReporters': [
        "clover",
        "json",
        "json-summary",
        "lcov",
        "text",
    ],
    'collectCoverageFrom': [
        "import/**/*.{js,jsx}",
        "!import/**/*.test.{js,jsx}",
    ],
}
